name: Run cargo tests
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.rs'
      - 'Cargo.toml'
      - 'tests/**/*'
  pull_request:
    paths:
      - '.github/workflows/test.yml'
      - 'src/**/*.rs'
      - 'Cargo.toml'
      - 'tests/**/*'
jobs:
  test:
    name: test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v5
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --verbose

  no-std:
    name: check (no_std + libm)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Install stable Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo check --verbose --no-default-features --features libm
